#POST http://localhost:8080/api/v1/sports/user
#Content-Type: application/json
#
#{
#  "username": "user4",
#  "nick": "user4",
#  "telegram": "@user4",
#  "password": "user_password3",
#  "role": "EXECUTOR"
#}
###

# Получить пользователя по username
GET http://localhost:8080/api/v1/sports/user/user2
Content-Type: application/json

###
#Создать исполнителя
#POST http://localhost:8080/api/v1/sports/user/executor
#Content-Type: application/json
#
#{
#  "username": "user3",
#  "passportSeriesNumber": "123456789",
#  "weight": 80.5,
#  "height": 180.3
#}

###

# Получить исполнителя по username
#GET http://localhost:8080/api/v1/sports/user/executor/user3
#Content-Type: application/json

###

# Обновить данные исполнителя
#PUT http://localhost:8080/api/v1/sports/user/executor
#Content-Type: application/json
#
#{
#  "username": "user3",
#  "passportSeriesNumber": "987654321",
#  "weight": 85.0,
#  "height": 182.0
#}

###
#Получить исполнителя по username
#POST  http://localhost:8080/api/v1/sports/user/city/change
#Content-Type: application/json
#
#{
#  "name": "Аксай",
#  "region": "Ростовская область"
#}

### Get all cities with pagination
#GET http://localhost:8080/api/v1/sports/user/city?page=0&size=10
#Accept: application/json

#### Delete a city by ID
#DELETE http://localhost:8080/api/v1/sports/admin/city/2

### Get mutilations
#GET http://localhost:8080/api/v1/sports/user/mutilation?page=0&size=50

#GET http://localhost:8080/api/v1/sports/user/mutilation/1

#POST  http://localhost:8080/api/v1/sports/user/mutilation/change
#Content-Type: application/json
#
#{
#  "type": "сломать ногу",
#  "price": 15000
#}
###
#PUT http://localhost:8080/api/v1/sports/user/mutilation/1
#Content-Type: application/json
#
#{
#  "type": "сломать ногу",
#  "price": 112222
#}

### Get VICTIM
#POST http://localhost:8080/api/v1/sports/user/victim
#Content-Type: application/json
#
#{
#  "firstName": "John",
#  "lastName": "Doe",
#  "workplace": "Office",
#  "position": "Manager",
#  "residence": "123 Street",
#  "phone": "123456789",
#  "description": "Sample description"
#}

###
# GET http://localhost:8080/api/v1/sports/user/victim?page=0&size=50

#GET http://localhost:8080/api/v1/sports/user/victim/1

### GET OPDER
#POST http://localhost:8080/api/v1/sports/user/order
#Content-Type: application/json
#
#{
#  "username": "user2",
#  "cityId": 1,
#  "victimId": 1,
#  "deadline": "2024-11-30",
#  "mutilationIds": [1]
#
#}
### Get Orders With Status Waiting
GET http://localhost:8080/api/v1/sports/user/order?page=0&size=50
Accept: application/json

### Get Orders By Username
#GET http://localhost:8080/api/v1/sports/user/order/user2?page=0&size=50
#Accept: application/json
###
#POST http://localhost:8080/api/v1/sports/user/fight
#Content-Type: application/json
#
#{
#  "executorId": "user3",
#  "orderId": 1
#}
###
#GET http://localhost:8080/api/v1/sports/user/fight/user3?page=0&size=50

PUT http://localhost:8080/api/v1/sports/user/fight/1/status?newStatus=VICTORY